### ISSUE TITLE
fMRIPrep-next checklist

### ISSUE THREAD

**Issue by effigies** [nipreps/smriprep#362]
This issue is just to start a checklist of things that need doing before we release a version intended for the major refactor of fMRIPrep. The current proposal is being tracked in the [next](https://github.com/nipreps/smriprep/tree/next) branch.

## Roadmap

* [ ] ...

## Cleanups

To move quickly and debug, I have made some changes that may need to be reverted or cleaned up before they go in production.

* [x] Python 3.8 compatibility (do we want to keep this?)
  * [ ] Type subscripting (e.g., `list[str]`) needs to be reverted to `typing` objects (e.g., `ty.List`)
* [x] Nipype configuration options
  * [x] Reset crashfiles to text
  * [x] Reset `remove_unnecessary_outputs`
  * [x] Reset `poll_sleep_duration`
